<?php


	
	
	
function menu_usuario()
{
	include ("../includes/languages/".LANGUAGE."");	
	return "
		<html>
		<head>
			 	<STYLE>
			<!--
				
				table {cursor:hand;}
			-->
			</STYLE>
		
			 	
		<script type='text/javascript' language='JavaScript1.2' src='../includes/javascript/menu.js'></script>
		</head>
		<body>
		
		
		<script type='text/javascript' language='JavaScript1.2'>
		<!--
		beginSTM('menu_usuario','static','0','0','none','false','true','310','0','0','250','','blank.gif');
			beginSTMB('auto','0','0','horizontally','arrow.gif','7','7','0','5','#92aecc','','tiled','#000000','0','solid','0','Normal','50','0','0','7','7','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
				appendSTMI('false','".$TRANS["inicio"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','Tela&nbsp;inicial','abertura.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','abertura.php','','','tiled','tiled');
				appendSTMI('false','".$TRANS["cadastro"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','','','','tiled','tiled');
				beginSTMB('auto','20','0','vertically','arrow_r.gif','0','0','0','2','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','0','0','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
					appendSTMI('false','".$TRANS["equip"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_equip"].".','./incluir_computador.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','./incluir_computador.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["documento"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_doc"].".','incluir_material.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','incluir_material.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["estoque"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_estoque"].".','incluir_estoque.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','incluir_estoque.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["local"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_local"].".','incluir_local.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','incluir_local.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["usuario"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_usuario"].".','incluir_usuario.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','incluir_usuario.php','','','tiled','tiled');
				endSTMB();
		
				appendSTMI('false','".$TRANS["visualiza"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','','','','tiled','tiled');
				beginSTMB('auto','20','0','vertically','arrow_r.gif','0','0','0','2','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','0','0','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
					appendSTMI('false','".$TRANS["equips"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_vs_equips"].".','mostra_consulta_comp.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','mostra_consulta_comp.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["docs"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_vs_docs"].".','materiais.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','materiais.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["estoqs"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_vs_estoq"].".','estoque.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','estoque.php','','','tiled','tiled');
				endSTMB();
		
				appendSTMI('false','".$TRANS["consulta"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','','','','tiled','tiled');
				beginSTMB('auto','20','0','vertically','arrow.gif','7','7','0','2','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','7','7','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
					appendSTMI('false','".$TRANS["cons_rapida"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cn_rapida"].".','consulta_inv.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','consulta_inv.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["cons_especial"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cn_especial"]."','consulta_comp.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','consulta_comp.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["cons_historico"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
					beginSTMB('auto','0','0','vertically','arrow_r.gif','0','0','0','3','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','0','0','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
						appendSTMI('false','".$TRANS["por_etiqueta"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_hist_etiq"].".','consulta_hist_inv.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','consulta_hist_inv.php','','','tiled','tiled');
						appendSTMI('false','".$TRANS["local_ant"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_hist_loc"].".','consulta_hist_local.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','consulta_hist_local.php','','','tiled','tiled');
					endSTMB();
				endSTMB();
				appendSTMI('false','".$TRANS["estatistica"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_estat"]."','relatorios.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','relatorios.php','','','tiled','tiled');
				appendSTMI('false','".$TRANS["senha"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_senha"]."','altera_senha.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','altera_senha.php','','','tiled','tiled');
				
				appendSTMI('false','".$TRANS["admin"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','','','','tiled','tiled');				
				beginSTMB('auto','20','0','vertically','arrow_desativada.gif','7','7','0','3','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','7','7','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
					appendSTMI('false','".$TRANS["componentes"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
					beginSTMB('auto','0','0','vertically','arrow_r.gif','0','0','0','3','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','0','0','0','0','0','#7f7f7f','false','#000000','#000000','#666666','none');
						appendSTMI('false','".$TRANS["cdrom"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["dvd"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["grav"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["hd"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["mb"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["memo"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["modem"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["proc"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["rede"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["som"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
						appendSTMI('false','".$TRANS["video"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
					endSTMB();
					appendSTMI('false','".$TRANS["fabricantes"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_fabricantes"]."','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
					appendSTMI('false','".$TRANS["fornecedores"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_fornecedores"]."','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
					appendSTMI('false','".$TRANS["configs"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_config"]."','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
					appendSTMI('false','".$TRANS["estoqs"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_vs_estoq"]."','','_self','Arial','9pt','#666666','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
				endSTMB();
				
				
				
				appendSTMI('false','".$TRANS["sair"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_sair"]."','./logout.php','_self','Arial','9pt','#ff0000','normal','normal','none','Arial','9pt','#ff0000','bold','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','./logout.php','','','tiled','tiled');
				appendSTMI('true','Imagem','left','middle','../includes/imgs/invmon.gif','../includes/imgs/invmon.gif','250','25','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["logo_invmon"]."','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#0000cc','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
			endSTMB();
		endSTM();
		//-->
		</script>
		
	
		
		</body>
		</html>
	";
}






function menu_usuario_admin() //admin
{
	include ("../includes/languages/".LANGUAGE."");
	return
	 " <html>
		<head>
		<script type='text/javascript' language='JavaScript1.2' src='../includes/javascript/menu.js'></script>
		</head>
		<body>
		<script type='text/javascript' language='JavaScript1.2'>
		<!--
		beginSTM('menu_usuario','static','0','0','none','false','true','310','0','0','250','','blank.gif');
			beginSTMB('auto','0','0','horizontally','arrow.gif','7','7','0','5','','','tiled','','0','solid','0','Normal','50','0','0','7','7','0','0','0','','false','','','','none');
				appendSTMI('false','".$TRANS["inicio"]."','left','middle','','','-1','-1','0','normal','','','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','Tela&nbsp;inicial','abertura.php','_self','Arial','9pt','','normal','normal','none','Arial','9pt','','normal','normal','none','1','solid','','','','','','','','','abertura.php','','','tiled','tiled');
				appendSTMI('false','".$TRANS["cadastro"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','','','','tiled','tiled');
				beginSTMB('auto','20','0','vertically','arrow_r.gif','0','0','0','2','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','0','0','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
					appendSTMI('false','".$TRANS["equip"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_equip"].".','./incluir_computador.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','./incluir_computador.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["documento"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_doc"].".','incluir_material.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','incluir_material.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["estoque"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_estoque"].".','incluir_estoque.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','incluir_estoque.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["local"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_local"].".','incluir_local.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','incluir_local.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["usuario"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cd_usuario"].".','incluir_usuario.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','incluir_usuario.php','','','tiled','tiled');
				endSTMB();
		
				appendSTMI('false','".$TRANS["visualiza"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','','','','tiled','tiled');
				beginSTMB('auto','20','0','vertically','arrow_r.gif','0','0','0','2','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','0','0','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
					appendSTMI('false','".$TRANS["equips"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_vs_equips"].".','mostra_consulta_comp.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','mostra_consulta_comp.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["docs"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_vs_docs"].".','materiais.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','materiais.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["estoqs"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_vs_estoq"].".','estoque.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','estoque.php','','','tiled','tiled');
				endSTMB();
		
				appendSTMI('false','".$TRANS["consulta"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','','','','tiled','tiled');
				beginSTMB('auto','20','0','vertically','arrow.gif','7','7','0','2','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','7','7','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
					appendSTMI('false','".$TRANS["cons_rapida"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cn_rapida"].".','consulta_inv.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','consulta_inv.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["cons_especial"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_cn_especial"]."','consulta_comp.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','consulta_comp.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["cons_historico"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
					beginSTMB('auto','0','0','vertically','arrow_r.gif','0','0','0','3','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','0','0','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
						appendSTMI('false','".$TRANS["por_etiqueta"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_hist_etiq"].".','consulta_hist_inv.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','consulta_hist_inv.php','','','tiled','tiled');
						appendSTMI('false','".$TRANS["local_ant"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_hist_loc"].".','consulta_hist_local.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','consulta_hist_local.php','','','tiled','tiled');
					endSTMB();
				endSTMB();
				appendSTMI('false','".$TRANS["estatistica"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_estat"]."','relatorios.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','relatorios.php','','','tiled','tiled');
				appendSTMI('false','".$TRANS["senha"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_senha"]."','altera_senha.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','altera_senha.php','','','tiled','tiled');
				appendSTMI('false','".$TRANS["admin"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','','','','tiled','tiled');
				beginSTMB('auto','20','0','vertically','arrow.gif','7','7','0','3','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','7','7','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
					appendSTMI('false','".$TRANS["componentes"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
					beginSTMB('auto','0','0','vertically','arrow_r.gif','0','0','0','3','#ffffff','','tiled','#000000','1','solid','0','Normal','50','0','0','0','0','0','0','0','#7f7f7f','false','#000000','#000000','#000000','none');
						appendSTMI('false','".$TRANS["cdrom"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=5','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=5','','','tiled','tiled');
						appendSTMI('false','".$TRANS["dvd"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=8','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=8','','','tiled','tiled');
						appendSTMI('false','".$TRANS["grav"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=9','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=9','','','tiled','tiled');
						appendSTMI('false','".$TRANS["hd"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=1','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=1','','','tiled','tiled');
						appendSTMI('false','".$TRANS["mb"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=10','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=10','','','tiled','tiled');
						appendSTMI('false','".$TRANS["memo"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=7','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=7','','','tiled','tiled');
						appendSTMI('false','".$TRANS["modem"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=6','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=6','','','tiled','tiled');
						appendSTMI('false','".$TRANS["proc"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=11','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=11','','','tiled','tiled');
						appendSTMI('false','".$TRANS["rede"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=3','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=3','','','tiled','tiled');
						appendSTMI('false','".$TRANS["som"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=4','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=4','','','tiled','tiled');
						appendSTMI('false','".$TRANS["video"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','','itens.php?tipo=2','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','itens.php?tipo=2','','','tiled','tiled');
					endSTMB();
					appendSTMI('false','".$TRANS["fabricantes"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_fabricantes"]."','fabricantes.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','fabricantes.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["fornecedores"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_fornecedores"]."','fornecedores.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','fornecedores.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["configs"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_config"]."','mostra_modelos_cadastrados.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','mostra_modelos_cadastrados.php','','','tiled','tiled');
					appendSTMI('false','".$TRANS["estoqs"]."','left','middle','','','-1','-1','0','normal','#92aecc','#000084','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_mn_vs_estoq"]."','estoque.php','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#ffffff','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','estoque.php','','','tiled','tiled');
				endSTMB();
				appendSTMI('false','".$TRANS["sair"]."','left','middle','','','-1','-1','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["hint_sair"]."','./logout.php','_self','Arial','9pt','#ff0000','normal','normal','none','Arial','9pt','#ff0000','bold','normal','none','1','solid','#92aecc','#92aecc','#ffffff','#666666','#92aecc','#92aecc','#666666','#ffffff','./logout.php','','','tiled','tiled');
				appendSTMI('true','Imagem','left','middle','../includes/imgs/invmon.gif','../includes/imgs/invmon.gif','250','25','0','normal','#92aecc','#92aecc','','1','-1','-1','blank.gif','blank.gif','-1','-1','0','".$TRANS["logo_invmon"]."','','_self','Arial','9pt','#0000cc','normal','normal','none','Arial','9pt','#0000cc','normal','normal','none','0','solid','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','#d6d6ce','','','','tiled','tiled');
			endSTMB();
		endSTM();
		//-->
		</script>
		</body>
		</html>
	";


	return $saída;
}


?>